### ISSUE TITLE
teleport not working correctly

### ISSUE THREAD

**Issue by Bobgy** [Bobgy/Latrop#2]
在垂直的墙壁上开传送门1, 在水平地面上开传送门2, 跳入地面上的传送门以后, 发现从墙上的传送门出来会垂直向上飞, 应该是水平往前飞

**Comment by Bobgy** [comment]
@zimpha

**Comment by zhujiale2** [comment]
![image](https://cloud.githubusercontent.com/assets/9071281/8414034/9b056d5c-1ec7-11e5-890e-686f6442236b.png)
should be like this
